---
name: "Setup Make"
description: "A composite action to set up to run Make"

inputs:
  repository:
    required: true
    description: "The repository to clone"
  branch:
    required: true
    description: "The branch to checkout"
  path:
    required: true
    description: "The path to clone the repository to"

runs:
  using: "composite"
  steps:
    - id: checkout_repository
      name: Checkout repository
      uses: actions/checkout@v4

    - id: checkout_repository_make
      name: Checkout repository for make
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}
        path: ${{ inputs.path }}

    - id: install_dependencies
      name: Install dependencies
      run: |
        apt update
        apt install -y make
