---
name: "Docker Buildx"
description: "A composite action to set up Docker Buildx"

inputs:
  registry:
    required: true
    description: "The registry to login to"
  username:
    required: true
    description: "The username to login to the registry"
  password:
    required: true
    description: "The password to login to the registry"

runs:
  using: "composite"
  steps:
    - id: dependencies
      name: Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - id: setup_qemu
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - id: setup_buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - id: login_to_registry
      name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - id: setup_crane
      name: Set up Crane
      uses: imjasonh/setup-crane@v0.4
