---
##################################################
#
# Name: dependabot.yml
# Description: Dependabot configuration for GitHub native version
# Reference: https://git.io/JJhjE
#
##################################################

version: 2

updates:
  #########################
  # GitHub Actions
  #########################

  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
      timezone: "Australia/Sydney"
    assignees:
      - "MAHDTech"
    reviewers:
      - "MAHDTech"
    labels:
      - "dependencies"
      - "dependabot"
      - "actions"
    target-branch: "trunk"
    commit-message:
      prefix: "github-actions"
    rebase-strategy: "auto"
    open-pull-requests-limit: 5
