---
name: Boot

on:
  workflow_call:
    inputs:
      registry:
        type: string
        required: true
        description: "The registry to push the packages to"
      username:
        type: string
        required: true
        description: "The username to login to the registry"
      password:
        type: string
        required: true
        description: "The password to login to the registry"
      token:
        type: string
        required: true
        description: "The token to use to authenticate with to GitHub"
      repository:
        type: string
        required: true
        description: "The repository to clone"
      branch:
        type: string
        required: true
        description: "The branch to checkout"
      path:
        type: string
        required: true
        description: "The path to checkout the repository to"
      talos_version:
        type: string
        required: true
        description: "The Talos version to make packages for"
      device:
        type: string
        required: true
        description: "The device to make packages for"

jobs:
  boot:
    name: Boot

    runs-on: self-hosted

    strategy:
      fail-fast: true

    steps:
      - id: dependencies
        name: Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y jq make

      - id: setup_qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - id: setup_buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: login_to_registry
        name: Login to registry (Docker)
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - id: crane_setup
        name: Set up Crane
        uses: imjasonh/setup-crane@v0.4

      - id: crane_login
        name: Login to registry (Crane)
        shell: bash
        env:
          CRANE_REGISTRY: ${{ inputs.registry }}
          CRANE_USERNAME: ${{ inputs.username }}
          CRANE_PASSWORD: ${{ inputs.password }}
        run: |
          echo "${CRANE_PASSWORD}" | crane auth login "${CRANE_REGISTRY,,}" --username "${CRANE_USERNAME}" --password-stdin

      - id: checkout_repository
        name: Checkout repository for make
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
          path: ${{ inputs.path }}

      - id: imager
        name: Run imager
        uses: ./.github/actions/imager
        with:
          token: ${{ inputs.token }}
          workdir: ${{ github.workspace }}/_make/overlay
          imager_image: ${{ inputs.registry }}/${{ inputs.username }}/imager:${{ inputs.talos_version }}-${{ inputs.device }}
          overlay_name: ${{ inputs.device }}
          overlay_image: ${{ inputs.registry }}/${{ inputs.username }}/sbc-rockchip:${{ inputs.talos_version }}-${{ inputs.device }}

      - id: upload_artifacts
        name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.device }}-${{ inputs.talos_version }}
          path: ${{ github.workspace }}/_make/overlay/_out/metal-${{ inputs.device }}-arm64.raw.xz
          if-no-files-found: error
          retention-days: 1
