---
name: Boot

on:
  workflow_call:
    inputs:
      registry:
        type: string
        required: true
        description: "The registry to push the packages to"
      username:
        type: string
        required: true
        description: "The username to login to the registry"
      talos_version:
        type: string
        required: true
        description: "The Talos version to make packages for"
      device:
        type: string
        required: true
        description: "The device to make packages for"

jobs:
  boot:
    name: Make Boot

    runs-on: self-hosted

    timeout-minutes: 1440
    continue-on-error: false

    strategy:
      fail-fast: true

    steps:
      - id: dependencies
        name: Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y jq make

      - id: setup_qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - id: setup_buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: login_to_registry
        name: Login to registry (Docker)
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ secrets.PAT_PACKAGES }}

      - id: crane_setup
        name: Set up Crane
        uses: imjasonh/setup-crane@v0.4

      - id: crane_login
        name: Login to registry (Crane)
        shell: bash
        env:
          CRANE_REGISTRY: ${{ inputs.registry }}
          CRANE_USERNAME: ${{ inputs.username }}
          CRANE_PASSWORD: ${{ secrets.PAT_PACKAGES }}
        run: |
          echo "${CRANE_PASSWORD}" | crane auth login "${CRANE_REGISTRY,,}" --username "${CRANE_USERNAME}" --password-stdin

      - id: imager_pull
        name: Pull imager image
        shell: bash
        env:
          IMAGER_IMAGE: ${{ inputs.registry }}/${{ inputs.username }}/imager:${{ inputs.talos_version }}-${{ inputs.device }}
        run: |
          docker image pull "${IMAGER_IMAGE,,}"

      - id: imager_run
        name: Run imager
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_PACKAGES }}
          IMAGER_IMAGE: ${{ inputs.registry }}/${{ inputs.username }}/imager:${{ inputs.talos_version }}-${{ inputs.device }}
          OVERLAY_NAME: ${{ inputs.device }}
          OVERLAY_IMAGE: ${{ inputs.registry }}/${{ inputs.username }}/sbc-rockchip:${{ inputs.talos_version }}-${{ inputs.device }}
        run: |
          docker run \
            --name imager \
            --rm \
            -t \
            --env GITHUB_TOKEN \
            --volume /dev:/dev \
            --mount type=bind,source="$(pwd)"/_out,target=/out \
            --privileged \
            "${IMAGER_IMAGE,,}" \
              "${OVERLAY_NAME}" \
              --arch arm64 \
              --overlay-name="${OVERLAY_NAME}" \
              --overlay-image="${OVERLAY_IMAGE}"

      - id: upload_artifacts
        name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.device }}-${{ inputs.talos_version }}
          path: ${{ github.workspace }}/_out/metal-arm64.raw.xz
          if-no-files-found: error
          retention-days: 1
