---
name: Cleanup

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read
  packages: write
  pull-requests: read
  statuses: read

env:
  REGISTRY: ghcr.io
  USER: MAHDTech
  ORGANISATION: ${{ github.repository_owner }}
  PROJECT: ${{ github.event.repository.name }}

  BRANCH_NAME_CURRENT: ${{ github.head_ref || github.ref_name }}
  BRANCH_NAME_DEFAULT: ${{ github.event.repository.default_branch }}

defaults:
  run:
    shell: bash

jobs:
  ##################################################
  # Cleanup
  ##################################################

  cleanup:
    name: Cleanup Packages

    runs-on: ${{ matrix.os }}

    timeout-minutes: 60
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest

    steps:
      - id: get_package_names
        name: Get package names
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_PACKAGES }}
        run: |
          PACKAGES=$(gh api \
            --header "Accept: application/vnd.github+json" \
            --header "X-GitHub-Api-Version: 2022-11-28" \
            /user/packages?package_type=container \
            | jq -r '.[] | select(.name) | .name')
          # shellcheck disable=SC2129
          echo "package_names<<EOF" >> "$GITHUB_OUTPUT"
          echo "$PACKAGES" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - id: delete_old_packages
        name: Delete old packages
        uses: smartsquaregmbh/delete-old-packages@v0.8.0
        with:
          type: container
          user: ${{ env.USER }}
          keep: 3
          token: ${{ secrets.PAT_PACKAGES }}
          dry-run: false
          names: ${{ steps.get_package_names.outputs.package_names }}

      - id: clear_cache
        name: Clear Actions Cache
        uses: easimon/wipe-cache@main
        with:
          dry-run: false
