---
name: Comments

on:
  issue_comment:
    types:
      - created
      - edited

permissions:
  issues: write
  pull-requests: write
  statuses: read

defaults:
  run:
    shell: bash

jobs:
  ##################################################
  # Send a notification to Discord
  ##################################################

  discord:
    name: Discord

    runs-on: ${{ matrix.os }}

    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: Post message to Discord
        id: discord_message
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_DISCORD }}
          PING: "@CI"
          MESSAGE: >
            The ${{ github.event_name }} event was triggered in the ${{ github.repository }} repository.
            The comment is available to view [here](${{ github.event.comment.html_url }})
        run: |
          sudo apt install jq --yes
          JSON_CONTENT=$(jq -n --arg 'content' "${PING} ${MESSAGE}" '$ARGS.named')
          curl \
          --verbose \
          --request POST \
          --header "Content-Type: application/json" \
          --data "${JSON_CONTENT}" \
          "$WEBHOOK_URL"
