---
name: Imager

on:
  workflow_call:
    inputs:
      token:
        type: string
        required: true
        description: "The token to use"
      workdir:
        type: string
        required: true
        description: "The working directory to use"
      imager_image:
        type: string
        required: true
        description: "The imager image to use"
      overlay_name:
        type: string
        required: true
        description: "The overlay name to use"
      overlay_image:
        type: string
        required: true
        description: "The overlay image to use"

jobs:
  imager:
    runs-on: ubuntu-latest
    steps:
      - id: imager_pull
        name: Pull imager image
        shell: bash
        env:
          IMAGER_IMAGE: ${{ inputs.imager_image }}
        run: |
          docker image pull "${IMAGER_IMAGE,,}"

      - id: imager_run
        name: Run imager
        shell: bash
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
          IMAGER_IMAGE: ${{ inputs.imager_image }}
          OVERLAY_NAME: ${{ inputs.overlay_name }}
          OVERLAY_IMAGE: ${{ inputs.overlay_image }}
        run: |
          docker run \
            --name imager \
            --rm \
            -t \
            --env GITHUB_TOKEN \
            --volume /dev:/dev \
            --mount type=bind,source="$(pwd)"/_out,target=/out \
            --privileged \
            "${IMAGER_IMAGE,,}" \
              "${OVERLAY_NAME}" \
              --arch arm64 \
              --overlay-name="${OVERLAY_NAME}" \
              --overlay-image="${OVERLAY_IMAGE}"
